#version 450
#extension GL_GOOGLE_include_directive : require

#define FRAME_COLOR_IMAGE_ACCESS writeonly

#include "ShaderBindings.glsl"

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint index = gl_GlobalInvocationID.x;

    ivec2 size = imageSize(colorBuffer);

    uint width = uint(size.x);
    uint height = uint(size.y);
    uint pixelCount = (width * height);

    if(index >= pixelCount) 
        return;

    uint x = (index % width);
    uint y = (index / width);

    vec3 color = vec3(0.1, 0.105, 0.115);

    imageStore(
        colorBuffer, 
        ivec2(int(x), int(y)), 
        vec4(color, 1.0)
    );
}
