/**
 * Copyright (C) 2026  Zarcx127@github.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 **/

#version 450
#extension GL_GOOGLE_include_directive : require

#define FRAME_COLOR_IMAGE_ACCESS writeonly

#include "ShaderBindings.glsl"

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint index = gl_GlobalInvocationID.x;

    ivec2 size = imageSize(colorBuffer);

    uint width = uint(size.x);
    uint height = uint(size.y);
    uint pixelCount = (width * height);

    if(index >= pixelCount) 
        return;

    uint x = (index % width);
    uint y = (index / width);

    vec3 color = vec3(0.1, 0.105, 0.115);

    imageStore(
        colorBuffer, 
        ivec2(int(x), int(y)), 
        vec4(color, 1.0)
    );
}
