/**
 * Copyright (C) 2026  Zarcx127@github.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 **/

#version 450
#extension GL_GOOGLE_include_directive : require

#define RADIX_HISTOGRAM_BUFFER_ACCESS
#define RADIX_SCAN_BLOCK_SUM_BUFFER_ACCESS writeonly
#define SPLAT_SORT_DISPATCH_BUFFER_ACCESS readonly
#define WORKGROUP_SCAN_LOCAL_SIZE SPLAT_SORT_SCAN_LOCAL_SIZE

#include "ShaderBindings.glsl"
#include "SplatConstants.glsl"
#include "SplatStructures.glsl"
#include "SplatWorkgroupScan.glsl"

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint localIndex = gl_LocalInvocationIndex;
    uint blockIndex = gl_WorkGroupID.x;
    uint bucketIndex = gl_WorkGroupID.y;

    uint workgroupCapacity = (
        uint(radixHistogramBuffer.values.length()) /
        SPLAT_SORT_RADIX_BUCKET_COUNT
    );

    uint activeWorkgroupCount = 
        sortDispatchBuffer.histogramBlocks.valueCount;

    uint scanBlockCapacityPerBucket = (
        uint(radixScanBlockSumBuffer.values.length()) /
        SPLAT_SORT_RADIX_BUCKET_COUNT
    );

    uint valueIndex = (
        (blockIndex * SPLAT_SORT_SCAN_LOCAL_SIZE) +
        localIndex
    );

    uint histogramIndex = (
        (bucketIndex * workgroupCapacity) +
        valueIndex
    );

    uint value = 0;
    if(valueIndex < activeWorkgroupCount)
        value = radixHistogramBuffer.values[histogramIndex];

    scanValues[localIndex] = value;

    barrier();

    workgroup_scan_upsweep();
    if(localIndex == 0)
    {
        uint finalIndex = SPLAT_SORT_SCAN_LOCAL_SIZE - 1;
        uint blockSumIndex = (
            (bucketIndex * scanBlockCapacityPerBucket) +
            blockIndex
        );

        radixScanBlockSumBuffer.values[blockSumIndex] = scanValues[finalIndex];
        scanValues[finalIndex] = 0;
    }

    barrier();

    workgroup_scan_downsweep();
    if(valueIndex < workgroupCapacity)
        radixHistogramBuffer.values[histogramIndex] = scanValues[localIndex];
}
