#version 450
#extension GL_GOOGLE_include_directive : require

layout(
    local_size_x = 16,
    local_size_y = 1,
    local_size_z = 1
) in;

layout(set = 2, binding = 14, std430) buffer RadixBucketOffsetBuffer
{
    uint values[];
}
radixBucketOffsetBuffer;

const uint SPLAT_SORT_RADIX_BUCKET_COUNT = 16;

shared uint scanValues[SPLAT_SORT_RADIX_BUCKET_COUNT];

void main()
{
    uint localIndex = gl_LocalInvocationIndex;

    scanValues[localIndex] =
        radixBucketOffsetBuffer.values[localIndex];

    barrier();

    for(
        uint offset = 1;
        offset < SPLAT_SORT_RADIX_BUCKET_COUNT;
        offset <<= 1
    ) {
        uint index = (
            ((localIndex + 1) * offset * 2) -
            1
        );

        if(index < SPLAT_SORT_RADIX_BUCKET_COUNT)
        {
            scanValues[index] +=
                scanValues[index - offset];
        }

        barrier();
    }

    if(localIndex == 0)
    {
        scanValues[
            SPLAT_SORT_RADIX_BUCKET_COUNT - 1
        ] = 0;
    }

    barrier();

    for(
        uint offset =
            SPLAT_SORT_RADIX_BUCKET_COUNT >> 1;

        offset > 0;
        offset >>= 1
    ) {
        uint index = (
            ((localIndex + 1) * offset * 2) -
            1
        );

        if(index < SPLAT_SORT_RADIX_BUCKET_COUNT)
        {
            uint leftValue =
                scanValues[index - offset];

            scanValues[index - offset] =
                scanValues[index];

            scanValues[index] += leftValue;
        }

        barrier();
    }

    radixBucketOffsetBuffer.values[localIndex] =
        scanValues[localIndex];
}
