/**
 * Copyright (C) 2026  Zarcx127@github.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 **/

#version 450
#extension GL_GOOGLE_include_directive : require

#define SPLAT_COUNTER_BUFFER_ACCESS readonly
#define SPLAT_ENTRY_RANGE_BUFFER_ACCESS
#define ENTRY_SCAN_BLOCK_SUM_BUFFER_ACCESS readonly

#include "ShaderBindings.glsl"
#include "SplatStructures.glsl"

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint entryIndex = gl_GlobalInvocationID.x;
    if(entryIndex >= counters.visibleCount)
        return;

    uint blockIndex = gl_WorkGroupID.x;

    splatEntryRangeBuffer.ranges[entryIndex].entryOffset +=
        entryScanBlockSumBuffer.values[blockIndex];
}
