#version 450
#extension GL_GOOGLE_include_directive : require

#define SPLAT_COUNTER_BUFFER_ACCESS readonly
#define SPLAT_ENTRY_RANGE_BUFFER_ACCESS
#define ENTRY_SCAN_BLOCK_SUM_BUFFER_ACCESS readonly

#include "ShaderBindings.glsl"
#include "SplatStructures.glsl"

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint entryIndex = gl_GlobalInvocationID.x;
    if(entryIndex >= counters.visibleCount)
        return;

    uint blockIndex = gl_WorkGroupID.x;

    splatEntryRangeBuffer.ranges[entryIndex].entryOffset +=
        entryScanBlockSumBuffer.values[blockIndex];
}
