#version 450
#extension GL_GOOGLE_include_directive : require

#define ENTRY_SCAN_BLOCK_SUM_BUFFER_ACCESS
#define WORKGROUP_SCAN_LOCAL_SIZE SPLAT_ENTRY_SCAN_LOCAL_SIZE

#include "ShaderBindings.glsl"
#include "SplatConstants.glsl"
#include "SplatWorkgroupScan.glsl"

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint localIndex = gl_LocalInvocationIndex;
    uint valueCount = uint(entryScanBlockSumBuffer.values.length());

    uint valuesPerThread = (
        (valueCount + SPLAT_ENTRY_SCAN_LOCAL_SIZE - 1) /
        SPLAT_ENTRY_SCAN_LOCAL_SIZE
    );

    uint firstValue = localIndex * valuesPerThread;
    uint finalValue = min(
        (firstValue + valuesPerThread), 
        valueCount
    );

    uint threadSum = 0;
    for(uint index = firstValue; index < finalValue; index++)
    {
        uint value = entryScanBlockSumBuffer.values[index];

        entryScanBlockSumBuffer.values[index] = threadSum;
        threadSum += value;
    }

    scanValues[localIndex] = threadSum;

    barrier();

    workgroup_scan_upsweep();
    if(localIndex == 0)
        scanValues[SPLAT_ENTRY_SCAN_LOCAL_SIZE - 1] = 0;

    barrier();

    workgroup_scan_downsweep();

    uint threadOffset = scanValues[localIndex];
    for(uint index = firstValue; index < finalValue; index++)
        entryScanBlockSumBuffer.values[index] += threadOffset;
}
