/**
 * Copyright (C) 2026  Zarcx127@github.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 **/

#version 450
#extension GL_GOOGLE_include_directive : require

#define ENTRY_SCAN_BLOCK_SUM_BUFFER_ACCESS
#define WORKGROUP_SCAN_LOCAL_SIZE SPLAT_ENTRY_SCAN_LOCAL_SIZE

#include "ShaderBindings.glsl"
#include "SplatConstants.glsl"
#include "SplatWorkgroupScan.glsl"

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint localIndex = gl_LocalInvocationIndex;
    uint valueCount = uint(entryScanBlockSumBuffer.values.length());

    uint valuesPerThread = (
        (valueCount + SPLAT_ENTRY_SCAN_LOCAL_SIZE - 1) /
        SPLAT_ENTRY_SCAN_LOCAL_SIZE
    );

    uint firstValue = localIndex * valuesPerThread;
    uint finalValue = min(
        (firstValue + valuesPerThread), 
        valueCount
    );

    uint threadSum = 0;
    for(uint index = firstValue; index < finalValue; index++)
    {
        uint value = entryScanBlockSumBuffer.values[index];

        entryScanBlockSumBuffer.values[index] = threadSum;
        threadSum += value;
    }

    scanValues[localIndex] = threadSum;

    barrier();

    workgroup_scan_upsweep();
    if(localIndex == 0)
        scanValues[SPLAT_ENTRY_SCAN_LOCAL_SIZE - 1] = 0;

    barrier();

    workgroup_scan_downsweep();

    uint threadOffset = scanValues[localIndex];
    for(uint index = firstValue; index < finalValue; index++)
        entryScanBlockSumBuffer.values[index] += threadOffset;
}
