#version 450
#extension GL_GOOGLE_include_directive : require

#include "SplatStructures.glsl"

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(set = 2, binding = 7, std430) readonly buffer SplatCounterBuffer
{
    uint visibleCount;
    uint entryCount;
    uint requestedEntryCount;
    uint overflowCount;
}
counters;

layout(set = 2, binding = 10, std430) buffer SplatEntryRangeBuffer
{
    SplatEntryRange ranges[];
}
splatEntryRangeBuffer;

layout(set = 2, binding = 11, std430) readonly buffer EntryScanBlockSumBuffer
{
    uint values[];
}
entryScanBlockSumBuffer;

void main()
{
    uint entryIndex = gl_GlobalInvocationID.x;
    if(entryIndex >= counters.visibleCount)
        return;

    uint blockIndex = gl_WorkGroupID.x;

    splatEntryRangeBuffer.ranges[entryIndex].entryOffset +=
        entryScanBlockSumBuffer.values[blockIndex];
}
