#version 450
#extension GL_GOOGLE_include_directive : require

#include "SplatStructures.glsl"

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(set = 2, binding = 7, std430) readonly buffer SplatCounterBuffer
{
    uint visibleCount;
    uint entryCount;
    uint requestedEntryCount;
    uint overflowCount;
}
counters;

layout(set = 2, binding = 10, std430) buffer SplatEntryRangeBuffer
{
    SplatEntryRange ranges[];
}
splatEntryRangeBuffer;

layout(set = 2, binding = 11, std430) writeonly buffer EntryScanBlockSumBuffer
{
    uint values[];
}
entryScanBlockSumBuffer;

const uint SPLAT_ENTRY_SCAN_LOCAL_SIZE = 256;

shared uint scanValues[SPLAT_ENTRY_SCAN_LOCAL_SIZE];

void main()
{
    uint localIndex = gl_LocalInvocationIndex;
    uint entryIndex = gl_GlobalInvocationID.x;

    scanValues[localIndex] = (
        (entryIndex < counters.visibleCount) 
            ? splatEntryRangeBuffer.ranges[entryIndex].entryCount 
            : 0
    );

    barrier();

    for(uint offset = 1; offset < SPLAT_ENTRY_SCAN_LOCAL_SIZE; offset <<= 1) 
    {
        uint index = (
            ((localIndex + 1) * offset * 2) - 1
        );

        if(index < SPLAT_ENTRY_SCAN_LOCAL_SIZE)
        {
            scanValues[index] +=
                scanValues[index - offset];
        }

        barrier();
    }

    if(localIndex == 0)
    {
        uint finalIndex = SPLAT_ENTRY_SCAN_LOCAL_SIZE - 1;

        entryScanBlockSumBuffer.values[gl_WorkGroupID.x] = 
            scanValues[finalIndex];

        scanValues[finalIndex] = 0;
    }

    barrier();

    for(uint offset = SPLAT_ENTRY_SCAN_LOCAL_SIZE >> 1; offset > 0; offset >>= 1) 
    {
        uint index = (
            ((localIndex + 1) * offset * 2) - 1
        );

        if(index < SPLAT_ENTRY_SCAN_LOCAL_SIZE)
        {
            uint leftValue = scanValues[index - offset];

            scanValues[index - offset] = scanValues[index];
            scanValues[index] += leftValue;
        }

        barrier();
    }

    if(entryIndex < counters.visibleCount)
    {
        splatEntryRangeBuffer.ranges[entryIndex].entryOffset =
            scanValues[localIndex];
    }
}
