#version 450
#extension GL_GOOGLE_include_directive : require

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(set = 2, binding = 11, std430) buffer EntryScanBlockSumBuffer
{
    uint values[];
}
entryScanBlockSumBuffer;

const uint SPLAT_ENTRY_SCAN_LOCAL_SIZE = 256;

shared uint threadSums[SPLAT_ENTRY_SCAN_LOCAL_SIZE];

void main()
{
    uint localIndex = gl_LocalInvocationIndex;
    uint valueCount = uint(entryScanBlockSumBuffer.values.length());

    uint valuesPerThread = (
        (valueCount + SPLAT_ENTRY_SCAN_LOCAL_SIZE - 1) /
        SPLAT_ENTRY_SCAN_LOCAL_SIZE
    );

    uint firstValue = localIndex * valuesPerThread;
    uint finalValue = min(firstValue + valuesPerThread, valueCount);

    uint threadSum = 0;

    for(uint index = firstValue; index < finalValue; index++)
    {
        uint value = entryScanBlockSumBuffer.values[index];

        entryScanBlockSumBuffer.values[index] = threadSum;
        threadSum += value;
    }

    threadSums[localIndex] = threadSum;

    barrier();

    for(uint offset = 1; offset < SPLAT_ENTRY_SCAN_LOCAL_SIZE; offset <<= 1) 
    {
        uint index = (
            ((localIndex + 1) * offset * 2) - 1
        );

        if(index < SPLAT_ENTRY_SCAN_LOCAL_SIZE)
        {
            threadSums[index] +=
                threadSums[index - offset];
        }

        barrier();
    }

    if(localIndex == 0)
        threadSums[SPLAT_ENTRY_SCAN_LOCAL_SIZE - 1] = 0;

    barrier();

    for(uint offset = SPLAT_ENTRY_SCAN_LOCAL_SIZE >> 1; offset > 0; offset >>= 1) 
    {
        uint index = (
            ((localIndex + 1) * offset * 2) - 1
        );

        if(index < SPLAT_ENTRY_SCAN_LOCAL_SIZE)
        {
            uint leftValue = threadSums[index - offset];

            threadSums[index - offset] = threadSums[index];
            threadSums[index] += leftValue;
        }

        barrier();
    }

    uint threadOffset = threadSums[localIndex];

    for(uint index = firstValue; index < finalValue; index++)
        entryScanBlockSumBuffer.values[index] += threadOffset;
}
