#version 450
#extension GL_GOOGLE_include_directive : require

#include "SplatStructures.glsl"

layout(
    local_size_x = 256,
    local_size_y = 1,
    local_size_z = 1
) in;

layout(set = 2, binding = 3, std430) readonly buffer SplatEntryKeyBufferA
{
    SplatEntryKey keys[];
}
entryKeyBufferA;

layout(set = 2, binding = 4, std430) readonly buffer SplatEntryKeyBufferB
{
    SplatEntryKey keys[];
}
entryKeyBufferB;

layout(set = 2, binding = 7, std430) readonly buffer SplatCounterBuffer
{
    uint visibleCount;
    uint entryCount;
    uint requestedEntryCount;
    uint overflowCount;
}
counters;

layout(set = 2, binding = 9, std430) buffer SplatTileRangeBuffer
{
    SplatTileRange ranges[];
}
tileRangeBuffer;

layout(push_constant) uniform TileRangePushConstants
{
    layout(offset = 112) uint sortedBufferIndex;
}
tileRangePushConstants;

const uint SPLAT_TILE_RANGE_LOCAL_SIZE = 256;

SplatEntryKey read_entry_key(uint entryIndex)
{
    if(tileRangePushConstants.sortedBufferIndex == 0)
        return entryKeyBufferA.keys[entryIndex];

    return entryKeyBufferB.keys[entryIndex];
}

void main()
{
    uint workgroupIndex = (
        gl_WorkGroupID.x +
        (gl_WorkGroupID.y * gl_NumWorkGroups.x)
    );

    uint entryIndex = (
        (workgroupIndex * SPLAT_TILE_RANGE_LOCAL_SIZE) +
        gl_LocalInvocationIndex
    );

    if(entryIndex >= counters.entryCount)
        return;

    SplatEntryKey currentKey =
        read_entry_key(entryIndex);

    uint currentTileIndex =
        currentKey.tileIndex;

    if(entryIndex == 0)
    {
        tileRangeBuffer.ranges[
            currentTileIndex
        ].startIndex = 0;
    }
    else
    {
        uint previousTileIndex =
            read_entry_key(entryIndex - 1).tileIndex;

        if(currentTileIndex != previousTileIndex)
        {
            tileRangeBuffer.ranges[
                previousTileIndex
            ].endIndex = entryIndex;

            tileRangeBuffer.ranges[
                currentTileIndex
            ].startIndex = entryIndex;
        }
    }

    if(entryIndex + 1 == counters.entryCount)
    {
        tileRangeBuffer.ranges[
            currentTileIndex
        ].endIndex = counters.entryCount;
    }
}
