/**
 * Copyright (C) 2026  Zarcx127@github.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 **/

#version 450
#extension GL_GOOGLE_include_directive : require

#define ENTRY_KEY_BUFFER_A_ACCESS readonly
#define ENTRY_KEY_BUFFER_B_ACCESS readonly
#define SPLAT_COUNTER_BUFFER_ACCESS readonly
#define SPLAT_TILE_RANGE_BUFFER_ACCESS

#include "SplatHelpers.glsl"
#include "ShaderBindings.glsl"
#include "SplatStructures.glsl"

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform TileRangePushConstants
{
    layout(offset = 112) 
    uint sortedBufferIndex;
}
tileRangePushConstants;

const uint SPLAT_TILE_RANGE_LOCAL_SIZE = 256;

void main()
{
    uint workgroupIndex = linear_workgroup_index(
        gl_WorkGroupID, 
        gl_NumWorkGroups
    );

    uint entryIndex = (
        (workgroupIndex * SPLAT_TILE_RANGE_LOCAL_SIZE) +
        gl_LocalInvocationIndex
    );

    if(entryIndex >= counters.entryCount)
        return;

    uint currentTileIndex = read_splat_entry_key(
        entryIndex,
        tileRangePushConstants.sortedBufferIndex
    ).tileIndex;

    if(entryIndex == 0)
    {
        tileRangeBuffer.ranges[currentTileIndex].startIndex = 0;
    }
    else
    {
        uint previousTileIndex = read_splat_entry_key(
            entryIndex - 1,
            tileRangePushConstants.sortedBufferIndex
        ).tileIndex;

        if(currentTileIndex != previousTileIndex)
        {
            tileRangeBuffer.ranges[previousTileIndex].endIndex = entryIndex;
            tileRangeBuffer.ranges[currentTileIndex].startIndex = entryIndex;
        }
    }

    if(entryIndex + 1 == counters.entryCount)
        tileRangeBuffer.ranges[currentTileIndex].endIndex = counters.entryCount;
}
